### ISSUE TITLE
Converting object to an encodable object failed: Instance of 'AppState'

### ISSUE THREAD

**Issue by Tacocopter** [Cretezy/redux_persist#36]
I'm having some trouble with the json serialization of my AppState, my code for fromJson and toJson is below. Could you help provide me with some insight into this issue?

Error:
```
[VERBOSE-2:shell.cc(184)] Dart Error: Unhandled exception:
Converting object to an encodable object failed: Instance of 'AppState'
#0      Persistor.save 
package:redux_persist/src/persistor.dart:182
<asynchronous suspension>
#1      Persistor.createMiddleware.<anonymous closure>.<anonymous closure> 
package:redux_persist/src/persistor.dart:67
#2      Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#3      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#4      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

Main:
```
void main() async {

  final persistor = Persistor<AppState>(
    storage: FlutterStorage(),
    serializer: JsonSerializer<AppState>(AppState.fromJson)
  );

  final initialState = await persistor.load();

  final store = new Store<AppState>(
    appReducer,
    initialState: initialState,
    middleware: []
      ..add(new LoggingMiddleware.printer())
      ..addAll(createAuthMiddleware())
      ..add(persistor.createMiddleware())
  );

  runApp(Flatmate(store: store));
}
```

AppState:
```
  static AppState fromJson(json) {
    print(json);
    if (json != null) {
      return AppState(
        authState: AuthState.fromJson(json['authState']),
      );
    } else {
      return AppState.initial();
    }
  }

  dynamic toJson() => 
    {
      'authState': authState.toJson(),
    };
```

AuthState:
```
  static AuthState fromJson(json) {
    return new AuthState(
      authStatus: json['authStatus'],
      loginError: json['loginError'],
      currentUser: json['currentUser'],
    );
  }

  dynamic toJson() =>
    {
      'authStatus': authStatus,
      'loginError': loginError,
      'currentUser': currentUser,
    };
```

**Comment by Cretezy** [comment]
This is quite weird, but I don't think it's caused by this library. It seems like the JSON encoder is having trouble encoding your AppState. I see that you have a `toJson` which looks correct, however maybe one of the sub-fields of AuthState isn't encodable.

Try manually creating an AppState and passing it to `json.encode` (from `dart:convert`) and tweaking with it until it works

**Comment by Cretezy** [comment]
Closing due to inactivity, feel free to reopen!

**Comment by MeFelixWang** [comment]
I got this problem too, did you find any method to deal with this? @Tacocopter
