### ISSUE TITLE
Converting object to an encodable object failed

### ISSUE THREAD

**Issue by remygautron** [Cretezy/redux_persist#45]
Hello, I have an error :

```
E/flutter (19502): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Converting object to an encodable object failed: Instance of 'ServicesState'
E/flutter (19502): #0      _JsonStringifier.writeObject (dart:convert/json.dart:645:7)
E/flutter (19502): #1      _JsonStringStringifier.printOn (dart:convert/json.dart:832:17)
E/flutter (19502): #2      _JsonStringStringifier.stringify (dart:convert/json.dart:817:5)
E/flutter (19502): #3      JsonEncoder.convert (dart:convert/json.dart:253:30)
E/flutter (19502): #4      JsonCodec.encode (dart:convert/json.dart:164:45)
E/flutter (19502): #5      JsonSerializer.encode (package:redux_persist/src/serialization.dart:28:35)
E/flutter (19502): #6      Persistor.save (package:redux_persist/src/persistor.dart:155:29)
E/flutter (19502): <asynchronous suspension>
E/flutter (19502): #7      Persistor.createMiddleware.<anonymous closure>.<anonymous closure> (package:redux_persist/src/persistor.dart:67:56)
E/flutter (19502): #8      _rootRun (dart:async/zone.dart:1120:38)
E/flutter (19502): #9      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (19502): #10     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (19502): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (19502): #12     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (19502): #13     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (19502): #14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
E/flutter (19502): #15     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
E/flutter (19502): #16     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
E/flutter (19502): #17     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
E/flutter (19502): #18     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
E/flutter (19502):
```

ServicesStates :

```dart
import 'package:pochoranet/components/Service.dart';

class ServicesState {

  List<Service> services;

  ServicesState({List<Service> services}){

    this.services = services ?? [];

  }

  ServicesState copyWith({List<Service> services}) => ServicesState(services: services ?? this.services);

  static ServicesState fromJson(dynamic json){

    if (json == null) return ServicesState();

    return ServicesState(services: json["services"] as List<Service>);

  }

  dynamic toJson() => {'services': services};

}
```

**Comment by Cretezy** [comment]
Hey sorry I forgot about this.

You should implement a `toJson` on `Service`, and do something like this:
```dart
  dynamic toJson() => {'services': services.map((service) => service.toJson()).toList()};
```

**Comment by HelaGone** [comment]
Hello @Cretezy 
How do you implement a `toJson` in the model? I've been trying this to work, but still get this error:
`Unhandled Exception: Converting object to an encodable object failed: Instance of 'AppState'` 

Here is my FavoriteItem class with its own toJson method:
```
class FavoriteItem{
  final String title, link, mediaUrl, type;
  final int id;
  final bool isFav;
  FavoriteItem({this.id, this.title, this.link, this.mediaUrl, this.isFav, this.type});

  Map toJson(FavoriteItem item){
   return {id: item.id, title: item.title, link: item.link, mediaUrl: item.mediaUrl, isFav:item.isFav, type: item.type};
  }
}
```
And here is my AppState:

```
class AppState {
  final List<FavoriteItem> favorites;
  final List<Post> news;
  final List<Post> reviews;
  final List<Podcast> podcasts;
  AppState({this.favorites, this.news, this.reviews, this.podcasts});
  AppState copyWith({List<FavoriteItem> copyFavs, List<Post> copyNews, List<Post> copyReviews, List<Podcast> copyPodcasts}){
    return AppState(
        favorites: copyFavs ?? this.favorites,
        news: copyNews ?? this.news,
        reviews: copyReviews ?? this.reviews,
        podcasts: copyPodcasts ?? this.podcasts
    );
  }
  static AppState fromJson(dynamic json){
    return AppState(favorites: json["favorites"] as List<FavoriteItem>);
  }
  dynamic toJson(){
    return {"favorites": favorites.map((favorite) => favorite.toJson(favorite)).toList() };
  }
}
```

I'm not sure what I'm doing wrong. Please point me in the right direction.

**Comment by Cretezy** [comment]
Okay so for the first:

```dart
class FavoriteItem{
  final String title, link, mediaUrl, type;
  final int id;
  final bool isFav;

  FavoriteItem({this.id, this.title, this.link, this.mediaUrl, this.isFav, this.type});

  toJson(){
    return {
      // Quotes are important here! "id" = "id", but id = the variable id's value
      "id": id,
      "title": title,
      "link": link,
      "mediaUrl": mediaUrl,
      "isFav": isFav,
      "type": type,
    };
  }

  static FavouriteItem fromJson(dynamic json) => FavouriteItem(
      id: json["id"],
      // ...
    );
}
```

and second:

```dart
class AppState {
  final List<FavoriteItem> favorites;
  final List<Post> news;
  final List<Post> reviews;
  final List<Podcast> podcasts;

  AppState({this.favorites, this.news, this.reviews, this.podcasts});

  AppState copyWith({List<FavoriteItem> favorites, List<Post> news, List<Post> reviews, List<Podcast> podcasts}){
    return AppState(
        favorites: favorites ?? this.favorites,
        news: news ?? this.news,
        reviews: reviews ?? this.reviews,
        podcasts: podcasts ?? this.podcasts
    );
  }

  static AppState fromJson(dynamic json){
    return AppState(
      favorites: (json["favorites"] as List)
        .map((favourite) => FavouriteItem.fromJson(favourite))
        .toList(),
    );
  }

  toJson(){
    return {
      "favorites": favorites
        .map((favorite) => favorite.toJson())
        .toList(),
     };
  }
}
```

Let me know if you have any question. If you compare yours vs this, you should be able to see which were the areas of trouble

**Comment by HelaGone** [comment]
Hell yeah!
Thanks for pointing me out in the right path. It's working good. Yesterday I got so close to your solution, but I was missing the fact that I need a fromJson in the model too!

Thanks Sir, you've earned a couple of beers!
